name: CI/CD for Static Website

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch
  pull_request:  # Also run CI for pull requests
    branches:
      - main

jobs:
  # Job 1: Continuous Integration
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Step 4: Lint HTML, CSS, and JavaScript
      - name: Lint JavaScript
        run: |
          npx eslint "**/*.js"

      - name: Lint CSS
        run: |
          npx stylelint "**/*.css"

      - name: Lint HTML
        run: |
          npx htmlhint "**/*.html"

      # Step 5: Run JavaScript tests (if applicable)
      - name: Run JavaScript tests
        run: |
          npm test

  # Job 2: Continuous Deployment
  cd:
    name: Continuous Deployment
    runs-on: ubuntu-latest
    needs: ci  # Run only if the 'ci' job succeeds

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Build the site (optional)
      - name: Build the site
        run: |
          npm run build

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Use './dist' if your build process generates files there
